services:
  database:
    image: mariadb:lts
    environment:
      MARIADB_ROOT_PASSWORD: amaris
      MARIADB_DATABASE: amaris
    container_name: test-amaris-db
    networks:
      - amaris-network
    ports:
      - 3306:3306
    volumes:
      - db-data:/var/lib/mysql
    command: --default-authentication-plugin=mysql_native_password
    restart: always
  api:
    build: .
    image: test-amaris-api:latest
    container_name: test-amaris-api
    networks:
      - amaris-network
    ports:
      - 3000:3000
    depends_on:
      - database
networks:
  amaris-network:
    name: amaris-network
volumes:
  db-data:
    name: test-amaris-db-data